# Generated by Django 3.1.1 on 2020-10-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=128, unique=True, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('city', models.CharField(max_length=128, verbose_name='город')),
                ('address', models.CharField(max_length=128, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
    ]
